### ISSUE TITLE
What is the version of tensorflow?

### ISSUE THREAD

**Issue by zzw1123** [zsdonghao/Unsup-Im2Im#10]
Hi,donghao,
I am running this project but I find there are so many errors at the beginning of my training,
e.g.
Traceback (most recent call last):
  File "train.py", line 362, in <module>
    tf.app.run()
  File "/home/zzw/Program/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 355, in main
    train_ac_gan()
  File "train.py", line 98, in train_ac_gan
    g_loss_fake = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(d_logits_fake, tf.ones_like(d_logits_fake)))
  File "/home/zzw/Program/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_impl.py", line 149, in sigmoid_cross_entropy_with_logits
    labels, logits)
  File "/home/zzw/Program/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1512, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `sigmoid_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

I guess these errors are due to differences between mine and yours,so could you please tell me what is the version of tensorflow?

**Comment by zsdonghao** [comment]
i think it is TF1.0+

**Comment by zzw1123** [comment]
Okay,I changed some arguments' order then the errors disappeared.
By the way,which conference is this paper contributed to?

**Comment by zsdonghao** [comment]
great. 
it is an arXiv paper
